const typesData = [
    "Accessories",
    "Adult",
    "Arts Craft Supplies",
    "Automotive",
    "Baby Toddler",
    "Bags Luggage",
    "Beauty",
    "Books",
    "Business Industrial",
    "CBD",
    "Clothing",
    "Computers",
    "Contact Lenses",
    "Custom Priniting",
    "Department Store",
    "E Cigarettes",
    "Education",
    "Electronics",
    "Entertainment",
    "Foods Beverages",
    "Footwear",
    "Fragrance",
    "Furniture",
    "Gifts Flowers",
    "Health Fitness",
    "Home Garden",
    "Home Kitchen",
    "Internet Service",
    "Jewelry",
    "Musica lnstruments",
    "Office Supplies",
    "Pet Supplies",
    "Photography",
    "Security Service",
    "Software",
    "Sports Outdoors",
    "Subscription Box",
    "Tobacoo",
    "Toys Games",
    "Travel",
    "Watches Sunglasses",
    "Web Hosting",
    "Wigs"
]  

export default typesData;