import logo from '../assets/images/Categoriesbased/logo.png'
import bg from '../assets/images/Categoriesbased/HouseofCB.png'

const CategoriesBasedCoupons = {
    Clothing: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 5,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 6,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 7,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 8,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
    ],
    Travel: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],
    Health_Fitness: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],
    Electronics: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],
    Home_Garden: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],
    Beauty: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],
    Food_Beverages: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],
    Accessories: [
        {
            id: 1,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 2,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 3,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },
        {
            id: 4,
            title: "Up To 25% Off Sale at House of CB",
            Verified: true,
            used: 10,
            coupon: "$58d^*d66",
            logo: logo,
            bg: bg,
        },

    ],

}

export default CategoriesBasedCoupons;